infos_data = [
    {'Posição': 1,
     'Nome de usuário': '@instagram',
     'Proprietário/a': 'Instagram',
     'Seguidores[2] (milhões)*': 648,
     'Profissão/Atividade': 'Rede social',
     'País': 'Estados Unidos'},
    {'Posição': 2, 'Nome de usuário': '@cristiano', 'Proprietário/a': 'Cristiano Ronaldo',
     'Seguidores[2] (milhões)*': 595, 'Profissão/Atividade': 'Futebolista', 'País': 'Portugal'},
    {'Posição': 3, 'Nome de usuário': '@leomessi', 'Proprietário/a': 'Lionel Messi', 'Seguidores[2] (milhões)*': 477,
     'Profissão/Atividade': 'Futebolista', 'País': 'Argentina'},
    {'Posição': 4, 'Nome de usuário': '@selenagomez', 'Proprietário/a': 'Selena Gomez', 'Seguidores[2] (milhões)*': 425,
     'Profissão/Atividade': 'Cantora, atriz e empresária', 'País': 'Estados Unidos'},
    {'Posição': 5, 'Nome de usuário': '@kyliejenner', 'Proprietário/a': 'Kylie Jenner', 'Seguidores[2] (milhões)*': 397,
     'Profissão/Atividade': 'Personalidade da televisão, modelo e empresária', 'País': 'Estados Unidos'},
    {'Posição': 6, 'Nome de usuário': '@therock', 'Proprietário/a': 'Dwayne Johnson', 'Seguidores[2] (milhões)*': 387,
     'Profissão/Atividade': 'Ator e ex-lutador profissional', 'País': 'Estados Unidos'},
    {'Posição': 7, 'Nome de usuário': '@arianagrande', 'Proprietário/a': 'Ariana Grande',
     'Seguidores[2] (milhões)*': 376, 'Profissão/Atividade': 'Cantora e atriz', 'País': 'Estados Unidos'},
    {'Posição': 8, 'Nome de usuário': '@kimkardashian', 'Proprietário/a': 'Kim Kardashian',
     'Seguidores[2] (milhões)*': 362, 'Profissão/Atividade': 'Personalidade da televisão, modelo e empresária',
     'País': 'Estados Unidos'},
    {'Posição': 9, 'Nome de usuário': '@beyonce', 'Proprietário/a': 'Beyoncé', 'Seguidores[2] (milhões)*': 314,
     'Profissão/Atividade': 'Cantora', 'País': 'Estados Unidos'},
    {'Posição': 10, 'Nome de usuário': '@khloekardashian', 'Proprietário/a': 'Khloé Kardashian',
     'Seguidores[2] (milhões)*': 310, 'Profissão/Atividade': 'Personalidade da televisão e modelo',
     'País': 'Estados Unidos'},
    {'Posição': 11, 'Nome de usuário': '@nike', 'Proprietário/a': 'Nike', 'Seguidores[2] (milhões)*': 301,
     'Profissão/Atividade': 'Empresa esportiva multinacional', 'País': 'Estados Unidos'},
    {'Posição': 12, 'Nome de usuário': '@justinbieber', 'Proprietário/a': 'Justin Bieber',
     'Seguidores[2] (milhões)*': 293, 'Profissão/Atividade': 'Cantor', 'País': 'Canadá'},
    {'Posição': 13, 'Nome de usuário': '@kendalljenner', 'Proprietário/a': 'Kendall Jenner',
     'Seguidores[2] (milhões)*': 292, 'Profissão/Atividade': 'Cantora, Personalidade de televisão e Modelo',
     'País': 'Estados Unidos'},
    {'Posição': 14,
     'Nome de usuário': '@natgeo',
     'Proprietário/a': 'National Geographic',
     'Seguidores[2] (milhões)*': 281,
     'Profissão/Atividade': 'Revista',
     'País': 'Estados Unidos'},
    {'Posição': 15, 'Nome de usuário': '@taylorswift', 'Proprietário/a': 'Taylor Swift',
     'Seguidores[2] (milhões)*': 267, 'Profissão/Atividade': 'Cantora', 'País': 'Estados Unidos'},
    {'Posição': 16, 'Nome de usuário': '@virat.kohli', 'Proprietário/a': 'Virat Kohli', 'Seguidores[2] (milhões)*': 254,
     'Profissão/Atividade': 'Jogador de críquete', 'País': 'Índia'},
    {'Posição': 17, 'Nome de usuário': '@jlo', 'Proprietário/a': 'Jennifer Lopez', 'Seguidores[2] (milhões)*': 249,
     'Profissão/Atividade': 'Cantora, atriz e empresária', 'País': 'Estados Unidos'},
    {'Posição': 18, 'Nome de usuário': '@kourtneykardash', 'Proprietário/a': 'Kourtney Kardashian',
     'Seguidores[2] (milhões)*': 223, 'Profissão/Atividade': 'Personalidade da televisão e modelo',
     'País': 'Estados Unidos'},
    {'Posição': 19, 'Nome de usuário': '@nickiminaj', 'Proprietário/a': 'Nicki Minaj', 'Seguidores[2] (milhões)*': 223,
     'Profissão/Atividade': 'Cantora', 'País': 'Trinidad e Tobago'},
    {'Posição': 20, 'Nome de usuário': '@mileycyrus', 'Proprietário/a': 'Miley Cyrus', 'Seguidores[2] (milhões)*': 212,
     'Profissão/Atividade': 'Cantora e atriz', 'País': 'Estados Unidos'},
    {'Posição': 21, 'Nome de usuário': '@neymarjr', 'Proprietário/a': 'Neymar', 'Seguidores[2] (milhões)*': 210,
     'Profissão/Atividade': 'Futebolista', 'País': 'Brasil'},
    {'Posição': 22, 'Nome de usuário': '@katyperry', 'Proprietário/a': 'Katy Perry', 'Seguidores[2] (milhões)*': 202,
     'Profissão/Atividade': 'Cantora', 'País': 'Estados Unidos'},
    {'Posição': 23, 'Nome de usuário': '@zendaya', 'Proprietário/a': 'Zendaya', 'Seguidores[2] (milhões)*': 183,
     'Profissão/Atividade': 'Atriz e cantora', 'País': 'Estados Unidos'},
    {'Posição': 24, 'Nome de usuário': '@kevinhart4real', 'Proprietário/a': 'Kevin Hart',
     'Seguidores[2] (milhões)*': 178, 'Profissão/Atividade': 'Humorista e ator', 'País': 'Estados Unidos'},
    {'Posição': 25, 'Nome de usuário': '@iamcardib', 'Proprietário/a': 'Cardi B', 'Seguidores[2] (milhões)*': 168,
     'Profissão/Atividade': 'Rapper e atriz', 'País': 'Estados Unidos'},
    {'Posição': 26, 'Nome de usuário': '@ddlovato', 'Proprietário/a': 'Demi Lovato', 'Seguidores[2] (milhões)*': 156,
     'Profissão/Atividade': 'Cantora e atriz', 'País': 'Estados Unidos'},
    {'Posição': 27, 'Nome de usuário': '@kingjames', 'Proprietário/a': 'LeBron James', 'Seguidores[2] (milhões)*': 156,
     'Profissão/Atividade': 'Basquetebolista', 'País': 'Estados Unidos'},
    {'Posição': 28, 'Nome de usuário': '@badgalriri', 'Proprietário/a': 'Rihanna', 'Seguidores[2] (milhões)*': 152,
     'Profissão/Atividade': 'Cantora e empresária', 'País': 'Barbados'},
    {'Posição': 29, 'Nome de usuário': '@chrisbrownofficial', 'Proprietário/a': 'Chris Brown',
     'Seguidores[2] (milhões)*': 142, 'Profissão/Atividade': 'Cantor', 'País': 'Estados Unidos'},
    {'Posição': 30, 'Nome de usuário': '@realmadrid', 'Proprietário/a': 'Real Madrid CF',
     'Seguidores[2] (milhões)*': 142, 'Profissão/Atividade': 'Clube de futebol', 'País': 'Espanha'},
    {'Posição': 31, 'Nome de usuário': '@champagnepapi', 'Proprietário/a': 'Drake', 'Seguidores[2] (milhões)*': 140,
     'Profissão/Atividade': 'Cantor', 'País': 'Canadá'},
    {'Posição': 32, 'Nome de usuário': '@ellendegeneres', 'Proprietário/a': 'Ellen DeGeneres',
     'Seguidores[2] (milhões)*': 139, 'Profissão/Atividade': 'Humorista e personalidade da televisão',
     'País': 'Estados Unidos'}, {'Posição': 33, 'Nome de usuário': '@fcbarcelona', 'Proprietário/a': 'FC Barcelona',
                                 'Seguidores[2] (milhões)*': 122, 'Profissão/Atividade': 'Clube de futebol',
                                 'País': 'Espanha'},
    {'Posição': 34, 'Nome de usuário': '@billieeilish', 'Proprietário/a': 'Billie Eilish',
     'Seguidores[2] (milhões)*': 109, 'Profissão/Atividade': 'Cantora', 'País': 'Estados Unidos'},
    {'Posição': 35, 'Nome de usuário': '@championsleague', 'Proprietário/a': 'UEFA Champions League',
     'Seguidores[2] (milhões)*': 107, 'Profissão/Atividade': 'Competição entre clubes de futebol',
     'País': 'União Europeia'},
    {'Posição': 36, 'Nome de usuário': '@k.mbappe', 'Proprietário/a': 'Kylian Mbappé', 'Seguidores[2] (milhões)*': 105,
     'Profissão/Atividade': 'Futebolista', 'País': 'França'},
    {'Posição': 37, 'Nome de usuário': '@gal_gadot', 'Proprietário/a': 'Gal Gadot', 'Seguidores[2] (milhões)*': 105,
     'Profissão/Atividade': 'Atriz', 'País': 'Israel'},
    {'Posição': 38, 'Nome de usuário': '@vindiesel', 'Proprietário/a': 'Vin Diesel', 'Seguidores[2] (milhões)*': 97,
     'Profissão/Atividade': 'Ator', 'País': 'Estados Unidos'},
    {'Posição': 39, 'Nome de usuário': '@lalalalisa_m', 'Proprietário/a': 'Lisa', 'Seguidores[2] (milhões)*': 955,
     'Profissão/Atividade': 'Rapper e Dançarina', 'País': 'Tailândia'},
    {'Posição': 40, 'Nome de usuário': '@nasa', 'Proprietário/a': 'NASA', 'Seguidores[2] (milhões)*': 939,
     'Profissão/Atividade': 'Agência espacial', 'País': 'Estados Unidos'},
    {'Posição': 41, 'Nome de usuário': '@dualipa', 'Proprietário/a': 'Dua Lipa', 'Seguidores[2] (milhões)*': 884,
     'Profissão/Atividade': 'Cantora', 'País': 'Reino Unido'},
    {'Posição': 42, 'Nome de usuário': '@priyankachopra', 'Proprietário/a': 'Priyanka Chopra',
     'Seguidores[2] (milhões)*': 884, 'Profissão/Atividade': 'Atriz e cantora', 'País': 'Índia'},
    {'Posição': 43, 'Nome de usuário': '@shakira', 'Proprietário/a': 'Shakira', 'Seguidores[2] (milhões)*': 877,
     'Profissão/Atividade': 'Cantora', 'País': 'Colômbia'},
    {'Posição': 44, 'Nome de usuário': '@nba', 'Proprietário/a': 'NBA', 'Seguidores[2] (milhões)*': 822,
     'Profissão/Atividade': 'Associação Nacional de Basquetebol', 'País': 'Estados Unidos'},
    {'Posição': 45, 'Nome de usuário': '@shraddhakapoor', 'Proprietário/a': 'Shraddha Kapoor',
     'Seguidores[2] (milhões)*': 815, 'Profissão/Atividade': 'Atriz', 'País': 'Índia'},
    {'Posição': 46, 'Nome de usuário': '@davidbeckham', 'Proprietário/a': 'David Beckham',
     'Seguidores[2] (milhões)*': 803, 'Profissão/Atividade': 'Ex-futebolista Presidente do Inter Miami',
     'País': 'Reino Unido'},
    {'Posição': 47, 'Nome de usuário': '@snoopdogg', 'Proprietário/a': 'Snoop Dogg', 'Seguidores[2] (milhões)*': 801,
     'Profissão/Atividade': 'Cantor', 'País': 'Estados Unidos'},
    {'Posição': 48, 'Nome de usuário': '@jennierubyjane', 'Proprietário/a': 'Jennie', 'Seguidores[2] (milhões)*': 80,
     'Profissão/Atividade': 'Cantora', 'País': 'Coreia do Sul'},
    {'Posição': 49, 'Nome de usuário': '@khaby00', 'Proprietário/a': 'Khaby Lame', 'Seguidores[2] (milhões)*': 796,
     'Profissão/Atividade': 'Celebridade da Internet', 'País': 'Senegal'},
    {'Posição': 50, 'Nome de usuário': '@gigihadid', 'Proprietário/a': 'Gigi Hadid', 'Seguidores[2] (milhões)*': 788,
     'Profissão/Atividade': 'Modelo', 'País': 'Estados Unidos'}]
